[[highlight]]
name = "timestamp"
regex = '(\d+:\d+.\d+|\w+ \d{2} \d{2}:\d{2}:\d{2})'
color = 'CYAN'

[[highlight]]
name = "syslogd"
regex = 'syslogd\[\d+\]'
color = 'RED'

[[highlight]]
name = "string"
regex = '".*"'
color = 'GREEN'

# [[highlight]]
# name = "digits"
# regex = '\d+'
# color = 'BLUE'

[[highlight]]
name = "word"
regex = '\d+\.\d+\.\d+\.\d+'
color = 'CYAN'
